import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { ts } from "ts-morph";
import type { AuditRule } from "../rule.js";
import { finding } from "./helpers.js";

export const modernTypeScriptRules: AuditRule[] = [
  {
    id: "NB-ARCH-013",
    code: "tsconfig-not-strict",
    architecture: "modern-typescript",
    defaultSeverity: "warn",
    stacks: ["next", "vite-react"],
    kind: "project",
    check(context) {
      return tsconfigStrict(context.rootDir) ? [] : [{
        rule: "NB-ARCH-013",
        sev: "warn",
        file: "tsconfig.json",
        line: 1,
        code: "tsconfig-not-strict",
      }];
    },
  },
  {
    id: "NB-ARCH-014",
    code: "explicit-any",
    architecture: "modern-typescript",
    defaultSeverity: "warn",
    stacks: ["next", "vite-react"],
    kind: "line",
    check(context) {
      return context.files.flatMap((file) => {
        if (
          /(\.d\.ts|\.test\.[jt]sx?|\.spec\.[jt]sx?)$/.test(file.path) ||
          file.path.startsWith("tests/") ||
          /(^|\/)(generated|__generated__)(\/|$)/.test(file.path) ||
          /(?:@generated|generated by (?:orval|openapi))/i.test(file.content.slice(0, 1000))
        ) {
          return [];
        }

        return file.lines.flatMap((line, index) =>
          /(:\s*any\b|as\s+any\b|<any>)/.test(line) ? [finding(file, "NB-ARCH-014", "explicit-any", index + 1)] : [],
        );
      });
    },
  },
];

function tsconfigStrict(rootDir: string): boolean {
  const visited = new Set<string>();
  return readStrictFromTsconfig(join(rootDir, "tsconfig.json"), visited) === true;
}

function readStrictFromTsconfig(path: string, visited: Set<string>): boolean | null {
  if (visited.has(path) || !existsSync(path)) {
    return null;
  }

  visited.add(path);

  const result = ts.parseConfigFileTextToJson(path, readFileSync(path, "utf8"));
  if (result.error || !isObject(result.config)) {
    return null;
  }

  const parsed = result.config as {
    extends?: string;
    compilerOptions?: { strict?: boolean };
  };

  if (parsed.compilerOptions?.strict !== undefined) {
    return parsed.compilerOptions.strict;
  }

  if (!parsed.extends) {
    return null;
  }

  if (parsed.extends.startsWith(".")) {
    const resolved = resolve(dirname(path), parsed.extends);
    return readStrictFromTsconfig(resolved.endsWith(".json") ? resolved : `${resolved}.json`, visited);
  }

  return null;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
