import { Node, SyntaxKind, type CallExpression, type SourceFile } from "ts-morph";
import type { AuditFile } from "../rule.js";
import type { AuditRule } from "../rule.js";
import { dataLayerGlobs, finding, isConfigFile, isDataLayerFile } from "./helpers.js";

export const typedContractRules: AuditRule[] = [
  {
    id: "NB-ARCH-007",
    code: "unvalidated-boundary",
    architecture: "typed-contracts",
    defaultSeverity: "warn",
    stacks: ["next", "vite-react"],
    kind: "ast",
    check(context) {
      const globs = dataLayerGlobs(context.ruleOptions);
      const configuredValidators = runtimeValidatorFunctions(context.ruleOptions);
      return context.files.flatMap((file) => {
        if (!isDataLayerFile(file, globs) || isGeneratedFile(file.path, file.content) || !file.sourceFile) {
          return [];
        }

        return unvalidatedBoundaryFindings(file, configuredValidators);
      });
    },
  },
  {
    id: "NB-ARCH-008",
    code: "env-outside-env-file",
    architecture: "typed-contracts",
    defaultSeverity: "warn",
    stacks: ["next", "vite-react"],
    kind: "line",
    check(context) {
      const envFiles = envFileGlobs(context.ruleOptions);
      return context.files.flatMap((file) => {
        if (isConfigFile(file.path) || envFiles.some((envFile) => file.path.endsWith(envFile))) {
          return [];
        }

        return file.lines.flatMap((line, index) => {
          const names = [...line.matchAll(/(?:process\.env|import\.meta\.env)\.([A-Z0-9_]+)/g)].map((match) => match[1] ?? "");
          return names.filter((name) => name !== "NODE_ENV").map((name) => finding(file, "NB-ARCH-008", "env-outside-env-file", index + 1, name));
        });
      });
    },
  },
];

function isGeneratedFile(path: string, content: string): boolean {
  return (
    /(^|\/)(generated|__generated__)(\/|$)/.test(path) ||
    /(?:@generated|generated by (?:orval|openapi))/i.test(content.slice(0, 1000))
  );
}

function unvalidatedBoundaryFindings(file: AuditFile, configuredValidators: Set<string>) {
  const sourceFile = file.sourceFile as SourceFile;
  const valibotValidators = importedValibotValidators(sourceFile);

  return sourceFile
    .getDescendantsOfKind(SyntaxKind.CallExpression)
    .filter(isJsonBoundaryCall)
    .filter((call) => !isBoundaryValidated(call, sourceFile, valibotValidators, configuredValidators))
    .map((call) => finding(file, "NB-ARCH-007", "unvalidated-boundary", call.getStartLineNumber()));
}

function isJsonBoundaryCall(call: CallExpression): boolean {
  const expression = call.getExpression();

  if (Node.isPropertyAccessExpression(expression)) {
    return (
      (expression.getName() === "json" && call.getArguments().length === 0) ||
      (expression.getExpression().getText() === "JSON" && expression.getName() === "parse")
    );
  }

  return false;
}

function isBoundaryValidated(
  boundary: CallExpression,
  sourceFile: SourceFile,
  valibotValidators: Set<string>,
  configuredValidators: Set<string>,
): boolean {
  if (
    boundary
      .getAncestors()
      .filter(Node.isCallExpression)
      .some((call) => isValidatorCall(call, valibotValidators, configuredValidators))
  ) {
    return true;
  }

  const declaration = boundary.getFirstAncestorByKind(SyntaxKind.VariableDeclaration);
  const nameNode = declaration?.getNameNode();
  if (!nameNode || !Node.isIdentifier(nameNode)) {
    return false;
  }

  const variableName = nameNode.getText();
  return sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression).some((call) => {
    if (!isValidatorCall(call, valibotValidators, configuredValidators)) {
      return false;
    }

    return call.getArguments().some(
      (argument) =>
        (Node.isIdentifier(argument) && argument.getText() === variableName) ||
        argument.getDescendantsOfKind(SyntaxKind.Identifier).some((identifier) => identifier.getText() === variableName),
    );
  });
}

function isValidatorCall(
  call: CallExpression,
  valibotValidators: Set<string>,
  configuredValidators: Set<string>,
): boolean {
  const expression = call.getExpression();

  if (Node.isPropertyAccessExpression(expression)) {
    return expression.getName() === "parse" || expression.getName() === "safeParse";
  }

  return (
    Node.isIdentifier(expression) &&
    (valibotValidators.has(expression.getText()) || configuredValidators.has(expression.getText()))
  );
}

function importedValibotValidators(sourceFile: SourceFile): Set<string> {
  const names = new Set<string>();

  for (const declaration of sourceFile.getImportDeclarations()) {
    if (declaration.getModuleSpecifierValue() !== "valibot") {
      continue;
    }

    for (const namedImport of declaration.getNamedImports()) {
      if (namedImport.getName() === "parse" || namedImport.getName() === "safeParse") {
        names.add(namedImport.getAliasNode()?.getText() ?? namedImport.getName());
      }
    }
  }

  return names;
}

function runtimeValidatorFunctions(options: Record<string, unknown>): Set<string> {
  const configured = options.runtimeValidatorFunctions;
  return new Set(
    Array.isArray(configured) && configured.every((item) => typeof item === "string") ? configured : [],
  );
}

function envFileGlobs(options: Record<string, unknown>): string[] {
  const configured = options.envFiles;
  return Array.isArray(configured) && configured.every((item) => typeof item === "string") ? configured : ["env.ts", "env.mjs"];
}
